[package]
name = "Sardinas-patterson-algorithm"
version = "0.1.0"
authors = ["Bernhard <34011017+Colfenor@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "sardinas-patterson"
path = "src/sardinas-patterson.rs"

[dependencies]
